version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vet
      POSTGRES_PASSWORD: vet
      POSTGRES_DB: vet
    ports:
      - "5432:5432"
  dbAdmin: 
    image: dpage/pgadmin4:8
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@vet.com
      PGADMIN_DEFAULT_PASSWORD: vet
    ports:
      - "5050:80"

volumes:
  postgres_data:
  pgadmin_data:
